/**
 * Generates docs/LOCATOR-COMPOSITION.md from the same three sources as the
 * patterns page: the prose in composition-patterns.mjs, the code in the scenario
 * that runs it, and the proofs that scenario recorded.
 *
 * Entirely generated, like docs/LOCATOR-REFERENCE.md. Nothing in it is worth
 * hand-editing, because everything in it is worth keeping in step with the test
 * that proves it.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { FAMILIES, PATTERNS } from './composition-patterns.mjs';
import { snippetsFor } from './snippets.mjs';

const SPEC = 'e2e/patterns/s14-composition.spec.ts';
const OUT = resolve(process.env.BM_COMPOSITION_DOC ?? 'docs/LOCATOR-COMPOSITION.md');
const PROOFS = resolve(process.env.BM_COMPOSITION ?? 'results/composition.json');

const fmtMs = (v) =>
  !Number.isFinite(v) ? '-'
  : v >= 1000 ? (v / 1000).toFixed(2) + ' s'
  : v >= 1 ? v.toFixed(1) + ' ms'
  : v.toFixed(3) + ' ms';

const { pairs, setup, missing } = snippetsFor(resolve(SPEC), PATTERNS);
if (missing.length) {
  console.error(`Missing example code in ${SPEC} for: ${missing.join(', ')}`);
  process.exit(1);
}

const file = existsSync(PROOFS) ? JSON.parse(readFileSync(PROOFS, 'utf8')) : null;
const proofs = file?.proofs ?? {};

const out = [];
const w = (...lines) => out.push(...lines);

/** Soft-wraps prose at the width the rest of the documentation uses. */
const wrap = (text) => text.replace(/(.{1,88})(\s|$)/g, '$1\n').trim();

w('# How locators compose');
w('');
w('Generated from `analysis/composition-patterns.mjs` and `' + SPEC + '`.');
w('Run `npm run composition-doc` after changing either. Do not edit this file.');
w('');
w('Every other document here measures one locator against one element. Nobody writes');
w('tests that way. A real suite hands a locator out of a fixture, chains onto it,');
w('stores it on a page object and indexes into it - and most of the ways a suite goes');
w('wrong live in that composition rather than in the choice of engine.');
w('');
w('Each pattern below is a DO/DON\'T pair that answers the same question both ways, and');
w('each one is proved by a scenario rather than asserted here:');
w('');
w('- **cost** - both forms work, and the DON\'T is measurably slower. Paired');
w('  measurement, baseline subtracted, median of the repetitions, same as every other');
w('  timing in this project.');
w('- **outcome** - the DON\'T is simply wrong. The proof is what it produced.');
w('');

if (file) {
  const proved = PATTERNS.filter((p) => proofs[p.id]).length;
  w(`Proofs below come from run \`${file.runId}\` on Chromium ${file.browserVersion ?? 'unknown'}: ` +
    `${proved} of ${PATTERNS.length} patterns.`);
} else {
  w('No proof file was present when this was generated, so the numbers are missing.');
  w('Run `npm run bench:patterns` and regenerate.');
}
w('');
w('```bash');
w('npm run bench:patterns   # writes results/composition.json');
w('npm run composition-doc  # rewrites this file');
w('```');
w('');
w('## What the examples are written against');
w('');
w('The examples share one scenario file, so they share its fixture and page object.');
w('`grid` below is that fixture. The page object hands out locators rather than');
w('elements, which is itself the first pattern.');
w('');
w('```ts');
w(setup.constants ?? '');
w('');
w(setup['page-object'] ?? '');
w('```');
w('');

for (const family of FAMILIES) {
  w(`## ${family.title}`);
  w('');
  w(wrap(family.lede));
  w('');

  for (const p of PATTERNS.filter((x) => x.family === family.id)) {
    const proof = proofs[p.id];
    w(`### ${p.title}`);
    w('');
    w(wrap(p.summary));
    w('');
    w('```ts');
    w('// DON\'T');
    w(pairs[p.id].dont);
    w('');
    w('// DO');
    w(pairs[p.id].do);
    w('```');
    w('');
    w(wrap(p.why));
    w('');
    if (proof?.kind === 'cost') {
      const ratio = proof.doMs > 0 ? (proof.dontMs / proof.doMs).toFixed(1) : '-';
      w(wrap(
        `**Measured** (${proof.domNodes.toLocaleString('en-US')} elements): ` +
        `${fmtMs(proof.dontMs)} to **${fmtMs(proof.doMs)}**, ${ratio} times faster. ` +
        `${p.proofNote}`,
      ));
      w('');
      w(`\`${proof.url}\``);
    } else if (proof) {
      w(wrap(
        `**Proved:** ${proof.dont}. Instead, ${proof.did}. ${p.proofNote}`,
      ));
      w('');
      w(`\`${proof.url}\``);
    } else {
      w('**Not proved on this run.**');
    }
    w('');
  }
}

w('## What this does not claim');
w('');
w('- The cost figures are one machine, one browser build, one page shape. The ratios');
w('  are the point, not the absolute milliseconds.');
w('- Nothing here says chaining, filtering or `nth()` are wrong. They are wrong in the');
w('  situations shown, for the reasons shown, and each pattern says what to do instead.');
w('- A pattern proved by outcome is proved for the case the scenario builds. That a');
w('  detached handle fails is a property of the API; that your suite has one is not');
w('  something this can tell you.');
w('');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.join('\n'));
console.log(`Wrote ${OUT} (${PATTERNS.length} patterns, ${Object.keys(proofs).length} proofs)`);
